### ISSUE TITLE
请求加入Energized Protection

### ISSUE THREAD

**Issue by xaver985** [Hackl0us/AdBlock-Rules-Mirror#1]
名称：Energized Protection
类型：本地hosts
作用：去广告
GitHub仓库地址： https://github.com/EnergizedProtection/block

**Comment by Hackl0us** [comment]
你好，感谢帮助完善项目。
不过鉴于规则已经托管在 GitHub，请参考 [完善项目 第 3 点](https://github.com/Hackl0us/AdBlock-Rules-Mirror#-完善项目) 来自行加速规则。
