### ISSUE TITLE
提交规则更新申请

### ISSUE THREAD

**Issue by marsxxl** [Hackl0us/AdBlock-Rules-Mirror#2]
1. EasyPrivacy，隐私保护，不被跟踪
地址：https://easylist.to/easylist/easyprivacy.txt

2. I don't care about cookies，屏蔽网站 cookies 的警告
地址：https://www.i-dont-care-about-cookies.eu/abp/

**Comment by Hackl0us** [comment]
感谢反馈，已经添加。
